<a href="https://colab.research.google.com/github/2303a51713/AIML-2025/blob/main/lab_1_Aiml_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
lst1=[9,4,7]
array1 = np.array(lst1)
array1

array([9, 4, 7])

In [3]:
type(lst1)

list

In [4]:
type(array1)


numpy.ndarray

In [6]:
list2=[4,6,1]
array2=np.array(list2)
array2

array([4, 6, 1])

In [7]:
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)
print(f" {array2} raised to the power of {array1}:,{array2**array1}")


array2 multiplied by array1:  [36 24  7]
array2 divided by array1:  [0.44444444 1.5        0.14285714]
array2 raised to the power of array1:  [262144   1296      1]
 [4 6 1] raised to the power of [9 4 7]:,[262144   1296      1]


In [8]:
# sine function
print("Sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))

Sine:  [ 0.41211849 -0.7568025   0.6569866 ]
Natural logarithm:  [2.19722458 1.38629436 1.94591015]
Base-10 logarithm:  [0.95424251 0.60205999 0.84509804]
Base-2 logarithm:  [3.169925   2.         2.80735492]
Exponential:  [8103.08392758   54.59815003 1096.63315843]


In [9]:
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)

Adding two numpy arrays {array1} and {array2} together: [13 10  8]


In [11]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")


Adding two numpy arrays [9 4 7] and [4 6 1] together: [13 10  8]
